FROM golang:1.6
RUN cd /usr/local/bin && wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.tar.gz && tar zxvf hugo*.tar.gz
ADD . /go/src/webshare
WORKDIR /go/src/webshare
RUN  go get github.com/jteeuwen/go-bindata/...
RUN go get github.com/elazarl/go-bindata-assetfs/...
RUN go-bindata-assetfs static/...
RUN go get ./...
RUN go build
