FROM golang:1.5
ADD . /go/src/webshare
WORKDIR /go/src/webshare
RUN  go get github.com/jteeuwen/go-bindata/...
RUN go get github.com/elazarl/go-bindata-assetfs/...
RUN go-bindata-assetfs static/...
RUN go get ./...
RUN go build
